### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by mostrovoi** [kubeflow-incubator/genspec#7]
Hi! 
I am trying to understand how to use this. 
In order to generate a valid swagger.json do I have to have a kubernetes cluster configured and the CRD installed? Where does it get the CRD definition from when creating the swagger.json? 

Thanks!
Oscar

**Comment by gaocegege** [comment]
https://github.com/kubeflow-incubator/genspec/blob/284555c2aece766d342f1f01b3793fdc8fe70619/pkg/spec/generator.go#L10

We hard-coded the crd here. I think.

BTW, this project is deprecated.

**Comment by mostrovoi** [comment]
ok, great. So no need of installing the CRD definition and get it via open api endpoint? 

I have a CRD definition and as part of my CI pipeline I would like to export it to openapi. i.e. swagger.json. Do you think I could use this (deprecated) project to get swagger.json from my CRD without having to install them in a k8s cluster?
Thanks!
Oscar

**Comment by gaocegege** [comment]
It is not needed to install the CRD first to generate the swagger.json
